// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package groclick

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/testcontainers/testcontainers-go"
)

// NewMockClickhouseContainer creates a new instance of MockClickhouseContainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClickhouseContainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClickhouseContainer {
	mock := &MockClickhouseContainer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClickhouseContainer is an autogenerated mock type for the ClickhouseContainer type
type MockClickhouseContainer struct {
	mock.Mock
}

type MockClickhouseContainer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClickhouseContainer) EXPECT() *MockClickhouseContainer_Expecter {
	return &MockClickhouseContainer_Expecter{mock: &_m.Mock}
}

// ConnectionString provides a mock function for the type MockClickhouseContainer
func (_mock *MockClickhouseContainer) ConnectionString(ctx context.Context, args ...string) (string, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, args)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ConnectionString")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) (string, error)); ok {
		return returnFunc(ctx, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) string); ok {
		r0 = returnFunc(ctx, args...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClickhouseContainer_ConnectionString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectionString'
type MockClickhouseContainer_ConnectionString_Call struct {
	*mock.Call
}

// ConnectionString is a helper method to define mock.On call
//   - ctx context.Context
//   - args ...string
func (_e *MockClickhouseContainer_Expecter) ConnectionString(ctx interface{}, args ...interface{}) *MockClickhouseContainer_ConnectionString_Call {
	return &MockClickhouseContainer_ConnectionString_Call{Call: _e.mock.On("ConnectionString",
		append([]interface{}{ctx}, args...)...)}
}

func (_c *MockClickhouseContainer_ConnectionString_Call) Run(run func(ctx context.Context, args ...string)) *MockClickhouseContainer_ConnectionString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockClickhouseContainer_ConnectionString_Call) Return(s string, err error) *MockClickhouseContainer_ConnectionString_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClickhouseContainer_ConnectionString_Call) RunAndReturn(run func(ctx context.Context, args ...string) (string, error)) *MockClickhouseContainer_ConnectionString_Call {
	_c.Call.Return(run)
	return _c
}

// Terminate provides a mock function for the type MockClickhouseContainer
func (_mock *MockClickhouseContainer) Terminate(ctx context.Context, opts ...testcontainers.TerminateOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Terminate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...testcontainers.TerminateOption) error); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClickhouseContainer_Terminate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Terminate'
type MockClickhouseContainer_Terminate_Call struct {
	*mock.Call
}

// Terminate is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...testcontainers.TerminateOption
func (_e *MockClickhouseContainer_Expecter) Terminate(ctx interface{}, opts ...interface{}) *MockClickhouseContainer_Terminate_Call {
	return &MockClickhouseContainer_Terminate_Call{Call: _e.mock.On("Terminate",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockClickhouseContainer_Terminate_Call) Run(run func(ctx context.Context, opts ...testcontainers.TerminateOption)) *MockClickhouseContainer_Terminate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []testcontainers.TerminateOption
		var variadicArgs []testcontainers.TerminateOption
		if len(args) > 1 {
			variadicArgs = args[1].([]testcontainers.TerminateOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockClickhouseContainer_Terminate_Call) Return(err error) *MockClickhouseContainer_Terminate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClickhouseContainer_Terminate_Call) RunAndReturn(run func(ctx context.Context, opts ...testcontainers.TerminateOption) error) *MockClickhouseContainer_Terminate_Call {
	_c.Call.Return(run)
	return _c
}
